# Generated by Django 3.2.5 on 2021-07-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(verbose_name='Actor date of the birth')),
                ('image', models.ImageField(upload_to='media/actors/image/', verbose_name='Actor photo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Category name')),
                ('description', models.TextField(verbose_name='Category description')),
                ('url', models.SlugField(max_length=300, verbose_name='Slug for category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Genre name')),
                ('description', models.TextField(verbose_name='Genre description')),
                ('url', models.SlugField(max_length=300, verbose_name='Slug for genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Movie name')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='media/movies/image', verbose_name='Title image for movie')),
                ('world_rating', models.PositiveSmallIntegerField(default=0, verbose_name='Movie world rating')),
                ('world_fees', models.PositiveIntegerField(verbose_name='Fees in world')),
                ('budget', models.PositiveIntegerField(verbose_name='Movie budget')),
                ('world_premier', models.DateField(verbose_name='Movie world premier')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('discription', models.TextField(verbose_name='Movie description')),
                ('url', models.SlugField(max_length=300, verbose_name='Slug for movie')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Movie likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Movie dislikes')),
                ('min_viewing_age', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=6)),
                ('actors', models.ManyToManyField(related_name='movie_actors', to='movies.Actor', verbose_name='Actors')),
                ('category', models.ManyToManyField(to='movies.Category', verbose_name='Category')),
                ('country', models.ManyToManyField(to='movies.Country', verbose_name='Movie country')),
                ('directors', models.ManyToManyField(related_name='movie_directors', to='movies.Actor', verbose_name='Directors')),
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='Movie genres')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=5000, verbose_name='Comment')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Review likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Review dislikes')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_to_movie', to='movies.movie')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.review', verbose_name='parent')),
            ],
        ),
    ]
