# Generated by Django 3.2.5 on 2021-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210828_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='biography',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Actor biography'),
        ),
    ]
