# Generated by Django 3.2.5 on 2021-08-28 17:15

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_actor_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_image',
            field=models.ImageField(upload_to=movies.models.Movie.movie_title_image_path_headler, verbose_name='Title image for movie'),
        ),
    ]
